<div class="container login-btn-block">
    <div class="row">
        <h1 style="width: 100%;margin-top:20px ">Terms of use</h1>
        <p>
            <i>Date of Last Revision: March 24, 2019</i>
            <br>
            <br>
            <b>Welcome to 180Credit.</b><br>
            180Credit’s products and services are provided by 180Credit, LLC. These terms and conditions of use ("Terms") govern your use of 180Credit's websites, mobile applications, products, and services (collectively, the "Services"), so please read them carefully.
            <br/>
            By accessing this website or using the Services, you are agreeing to the Terms, 180Credit's Privacy Policy and 180Credit's Community Guidelines. If you have any questions, please contact us.
            <br><br>
            <b>1. Using our services</b><br>
            You may use our Services only if you can form a binding contract with 180Credit. No use of the Services is permitted by those under the age of majority in their state of residence. In no event is use of the Services permitted by those under the age of 18. If you are using the Services on behalf of any entity, then you are agreeing to the Terms on behalf of that entity.<br/>
            Using our Services does not give you ownership of any intellectual property rights in our Services or the content you access. Except in the context of browsing or accessing our Services in accordance with these Terms, you may not use content from our Services unless you obtain permission from its owner or are otherwise permitted by law. These Terms do not grant you the right to use any branding or logos used in our Services. Do not remove, obscure, or alter any legal notices displayed in or along with our Services.<br/>
            Do not use our Services on any mobile device in a way that distracts you and prevents you from obeying traffic or safety laws.
            <br><br><b>2. Information on the services</b><br>
            Our Services display both 180Credit-created content and content that is not created or developed by 180Credit (the "Credit Repair Specialist Information"). We may review third party-content to determine whether it is illegal or violates our policies, and we may remove or refuse to display content that we reasonably believe violates our policies or the law. But we do not routinely screen third-party content that is published via our Services. This includes the Credit Repair Specialist Information that credit repair specialists and industry service providers post on 180Credit, and we cannot guarantee the accuracy, adequacy or quality of any such Credit Repair Specialist Information, or the qualifications of those posting it.
            <br><br><b>3. No formation of a specialist-client relationship</b><br>
            The Credit Repair Specialist Information found on 180Credit is intended for general informational purposes only and should be used only as a starting point for addressing your legal issues. The Credit Repair Specialist Information is not the provision of credit repair services, and accessing such information, or corresponding with or asking questions to a specialist the Services, or otherwise using the Services, does not create a specialist-client relationship between you and 180Credit, or you and any specialist. It is not a substitute for an in-person or telephone consultation with a specialist licensed to perform credit repair related services in your jurisdiction, and you should not rely on such Credit Repair Specialist Information. You understand that questions and answers or other postings to the Services are not confidential.
            <br><br><b>4. Legal services for consumers</b><br>
            180Credit is a platform where credit repair professionals unaffiliated with 180Credit can offer information and interact with consumers. We provide a number of methods by which you can purchase legal services or have a direct, confidential discussion of your legal issues with a lawyer. Although some of these methods involve 180Credit processing a transaction on your behalf, in all instances, 180Credit is simply the intermediary in such transactions. You are liable for paying the lawyer for the services provided. 180Credit has no liability, either primarily or secondarily, for paying the lawyer other than as an agent on your behalf. The fees you pay for such services are charged by the lawyer and passed through to the lawyer once services have been rendered. Any attorney-client relationship formed as a result of such discussions is between you and the lawyer you speak with—not between you and 180Credit. Furthermore, you understand that 180Credit cannot be held responsible for the quality or accuracy of any information or legal services provided by lawyers you connect with via 180Credit.
            <br><br><b>5. Premium services for credit repair professionals and service providers</b><br>
            180Credit offers optional Premium Services for lawyers. By selecting a Premium Service you agree to pay 180Credit the subscription or usage fees indicated for that service. Payments for subscription services will be charged on the day your Premium Service goes into effect and will cover the use of that service for the period indicated. Thereafter, you agree that monthly payments will continue to be charged to your credit card on a recurring basis until you cancel your service. The amount of the monthly recurring charge will be the then-current subscription fee applicable to the Premium Service you selected. You acknowledge that the amount of the recurring charge may increase if the applicable subscription fee increases. Premium Services other than advertising, websites, or Ignite must be cancelled prior to your monthly renewal in order to avoid billing of the next month's Premium Service fee. For advertising services, websites, or Ignite, 180Credit must receive written notice of your cancellation or reduction in service at least thirty (30) days in advance of the monthly renewal date on which you wish to make the cancellation or reduction effective. All cancellations or reductions of advertising services must be received in writing by email (cancel.ads@180Credit.com) or by U.S. mail (720 Olive Way, Suite 1400, Seattle, WA 98101 ATTN: Cancellations). Premium Service fees are not prorated or refundable.<br/>
            If your payment method fails or your account is past due, 180Credit reserves the right to either suspend or terminate your Premium Services. Any such suspension or termination will result in the cancellation of any promotional programs applicable to your Premium Services. You agree to submit any disputes regarding any charge to your account in writing to 180Credit within sixty (60) days of such charge, otherwise such dispute will be waived and such charge will be final and not subject to challenge.<br/>
            Premium Services may include the publication of advertising or website content you provide to us (the “Premium Services Content”). You retain all rights in, and are solely responsible for, the Premium Services Content posted on 180Credit or websites supported by 180Credit. You give 180Credit, our affiliates, providers of third party services, and subcontractors a non-exclusive, fully-paid, perpetual, royalty-free, transferable, revocable, worldwide license to use, modify, publicly perform, publicly display, reproduce, and distribute the Premium Services Content (in whole or in part) in providing the Services.<br/>
            <br><br><b>6. Legal advertising and communications</b><br>
            It is solely the responsibility of lawyers and law firms to ensure that any information or advertisements they post or place on the 180Credit website (including without limitation any Legal Information), and any communications they may have with prospective clients through the Services, fully complies with all applicable laws and rules of professional conduct, including those concerning the unauthorized practice of law and those regulating the form, manner or content of communications with clients, advertising, or other matters.
            <br><br><b>7. Copyright</b><br>
            We respond to notices of alleged copyright infringement and terminate accounts of repeat infringers according to the process set out in the U.S. Digital Millennium Copyright Act.<br/>
            If you believe that any material on the Site infringes upon any copyright which you own or control, you may file a DMCA Notice of Alleged Infringement with 180Credit's Designated Copyright Agent:<br/>
            180Credit Copyright Agent<br/>
            c/o 180Credit Legal Department / Robert Jenkins<br/>
            1425 West High Street, Haddon Heights NJ 08035<br/>
            Telephone: (800) 555-1212<br/>
            email: legal@180Credit.com<br/>
            <br><br><b>8. Disclaimers and acknowledgements regarding use of legal information</b><br>
            While 180Credit strives to provide—and to allow credit repair specialists to provide—useful information regarding credit repair and related services, there are some things that we cannot guarantee. You acknowledge that such information consists of third party data and contributions, that there are certain inherent limitations to the accuracy or currency of such information, that Credit Specialist Information may be incomplete, may contain inaccuracies, or may be based on opinion. 180Credit DOES NOT SCREEN SUCH INFORMATION FOR ACCURACY OR RELIABILITY. TO THE FULLEST EXTENT PERMITTED BY LAW, 180Credit AND ITS AFFILIATES, SUPPLIERS AND DISTRIBUTORS MAKE NO WARRANTIES, EITHER EXPRESS OR IMPLIED, ABOUT THE SERVICES OR SOFTWARE. THE SERVICES AND SOFTWARE ARE PROVIDED "AS IS." 180Credit ALSO DISCLAIMS ANY WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT.
            <br><br><b>9. Limitation of liability</b><br>
            TO THE FULLEST EXTENT PERMITTED BY LAW, IN NO EVENT SHALL 180CREDIT OR ANY OF ITS AFFILIATES, SUPPLIERS AND DISTRIBUTORS, OR ANY OF THEIR RESPECTIVE DIRECTORS, EMPLOYEES AND AGENTS, BE LIABLE FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES, OR ANY LOSS OF PROFITS OR REVENUES, WHETHER INCURRED DIRECTLY OR INDIRECTLY, OR ANY LOSS OF DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES, RESULTING FROM (A) THE OUTCOME OF ANY LEGAL MATTER; (B) YOUR ACCESS TO OR USE OF OR INABILITY TO ACCESS OR USE THE SERVICES OR SOFTWARE; (C) ANY CONDUCT OR CONTENT OF ANY THIRD PARTY RELATING TO THE SERVICES OR SOFTWARE; OR (D) UNAUTHORIZED ACCESS, USE OR ALTERATION OF LEGAL INFORMATION.<br/>
            TO THE EXTENT PERMITTED BY LAW, THE TOTAL LIABILITY OF 180CREDIT, AND ITS AFFILIATES, SUPPLIERS AND DISTRIBUTORS, FOR ANY CLAIM ARISING OUT OF OR RELATING IN ANY MANNER TO THE USE OF THE SERVICES OR SOFTWARE, IS LIMITED TO THE AMOUNT YOU PAID US TO USE THE SERVICES TO WHICH SUCH CLAIM RELATES IN THE 12 MONTH PERIOD PRECEDING THE FILING OF SUCH CLAIM. IN THE INTEREST OF CLARITY, THIS LIMITATION ALSO APPLIES TO PREMIUM SERVICES.
            <br><br><b>10. User posted content & other interactive services or areas</b>
            180Credit includes interactive areas in which you may post content and information, including peer endorsements and user reviews, questions and answers, comments, photos, and other materials (the "User Content"). You retain all rights in, and are solely responsible for, the User Content you post to 180Credit. You are also solely responsible for your use of such interactive features, and use them at your own risk. By using any interactive feature, you agree to comply with the 180Credit Community Guidelines. We reserve the right to remove or modify User Content for any reason, including User Content that we believe violates these Terms or our policies.<br/>
            When you post User Content to 180Credit, you give 180Credit and its affiliates a nonexclusive, royalty-free, perpetual, irrevocable and fully sublicensable right to use, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, perform and display such User Content throughout the world in any media. To the extent such content is attached to a profile on the 180Credit platform, the foregoing license includes a right to reproduce your profile, and any name, likeness or photograph contained in such profile. If you submit feedback or suggestions about our Services, we may use your feedback or suggestions without obligation to you.
            <br><br><b>11. Indemnification</b><br>
            You agree to defend, indemnify and hold harmless 180Credit, its corporate affiliates, independent contractors, service providers and consultants, and each of their respective directors, employees and agents, from and against any claims, damages, costs, liabilities and expenses (including, but not limited to, reasonable attorneys' fees) arising out of or related to any User Content you post, store or otherwise transmit on or through the Services or your use of or inability to use the Services, including without limitation any actual or threatened suit, demand or claim arising out of or relating to the User Content, your conduct, your violation of these Terms or your violation of the rights of any third party.
            <br><br><b>12. Modifications</b><br>
            180Credit may revise these Terms from time to time, on a prospective basis, and we will always post the most up-to-date version on our website. If we determine, in our sole discretion, that a modification to these Terms materially affects your rights, we will notify you (by, for example, sending a message to your account email). By using or continuing to use or access the Services after any revisions have come into effect, you agree to be bound by the revised Terms.
            <br><br><b>13. Mandatory Arbitration and Dispute Resolution</b><br>
            PLEASE READ THIS SECTION CAREFULLY, AS IT AFFECTS YOUR RIGHTS.<br/>
            We hope we never have a dispute, but if we do, you and we agree to try for 60 days to resolve it informally. You may send us the details of your concern to legal@180Credit.com.  However, if 180Credit is not able to informally resolve your complaint, you and 180Credit agree to <b>individual binding arbitration under JAMS Alternative Dispute resolution (“JAMS”) and the Federal Arbitration Act (“FAA”), and not to sue in court in front of a judge or jury. </b> The arbitration will be conducted under the JAMS Commercial Arbitration Rules and the Supplementary Procedures for Consumer Related Disputes and the arbitrator’s decision will be final except for a limited right of review under the FAA. The following applies to any arbitration proceedings between you and 180Credit:<br/>
            Before moving an unresolved informal dispute into arbitration, you must first send us a Notice of Dispute describing the nature and basis of the claim or dispute and the specific relief sought. This notice may be sent via email or U.S. mail to: legal@180Credit.com or 180Credit, Inc., Attention General Counsel, 720 Olive Way, #1400, Seattle, WA 98112.<br/>
            Any arbitration must be commenced by filing a demand for arbitration with JAMS within ONE (1) YEAR from when it first could be filed. Otherwise, it is permanently barred. If applicable law prohibits a one-year limitation period for asserting claims, any claim must be asserted within the shortest time period permitted by applicable law.<br/>
            Whenever feasible, the arbitration will be held telephonically unless the arbitrator finds good cause to hold an in-person hearing instead. You may choose the location of any in-person hearing from either your county of residence; or, if you are a business, the county of your principal place of business; or, 180Credit’s principal place of business in King County, WA.<br/>
            The enforcement of the arbitrator’s award will be controlled by and conducted in conformity with the FAA. Judgment upon any award may be entered in any court holding jurisdiction.<br/>
            Notwithstanding our agreement to arbitrate disputes as provided above, the following EXCEPTIONS will apply to the resolution of disputes between us:<br/>
            <b>Small Claims Court.</b> If the claim qualifies, either you or 180Credit may bring an action in small claims court in King County, WA. Any small claims court action must be filed within one year from when it first could be filed. Otherwise, the claim is permanently barred.<br/>
            <b>Injunctive relief.</b> 180Credit may bring a lawsuit against you in any court of competent jurisdiction solely for <b>injunctive relief to stop any unauthorized use or abuse of the Services, or any intellectual property infringement. </b> In these instances, 180Credit may seek injunctive relief without first engaging in the informal dispute resolution or arbitration process, as described above in these Terms of Use.<br/>
            <b>Disputes not Covered by Arbitration.</b> In the event that arbitration is found to be inapplicable or unenforceable for any reason, or if you exercise the option to opt-out of arbitration as provided below, the claim at issue will be brought under judicial proceedings in federal or state courts in King County, WA, and you and 180Credit consent to personal jurisdiction and exclusive venue in such courts.<br/>
            <b>Option to Opt Out of Arbitration.</b> You may opt out of this agreement to arbitrate. If you do so, neither you nor 180Credit can require the other to participate in an arbitration proceeding. To opt out, you must notify us in writing within 30 days of the date that you first became subject to the arbitration provision in these Terms. To opt out you must send us a clear statement that you want to opt out of arbitration, along with your name, residence or business address, and the email address associated with your account to: legal@180Credit.com.<br/>
            <b>NO CLASS ACTIONS: You may only bring individual claims. Under no circumstances are you allowed to bring a claim as a plaintiff or a class member in a class. Class action lawsuits, class-wide arbitrations, private attorney-general actions, and any other proceedings where someone acts in a representative capacity are not allowed. Any combining of individual proceedings must have the consent of all parties.</b><br/>
            <br><br><b>14. Applicable law</b><br>
            The laws of the State of Washington, excluding its conflict of law provisions, will apply to any disputes arising out of or relating to these Terms or the Services. 
            <br><br><b>15. Termination</b><br>
            Notwithstanding any of these Terms, 180Credit reserves the right, without notice and in its sole discretion, to terminate your license to use the Services, and to block or prevent your access to and use of the Services. 180Credit reserves the right to refuse service to anyone for any reason at any time. In the event of termination of access to the Services for any reason, you have no right to obtain a copy of any data or communications you stored or effected via the Services, or any other data.
            <br><br><b>16. Entire agreement</b><br>
            These Terms constitute the entire agreement between you and 180Credit with respect to the subject matter of these Terms, and supersede and replace any prior version of the Terms. These Terms create no third party beneficiary rights.
            <br><br><b>17. Waiver, severability, and assignment</b><br>
            180Credit's failure to enforce a provision of these Terms is not a waiver of its right to do so later. If any provision of these Terms is found unenforceable, the remaining provisions of the Terms will remain in full effect and an enforceable Term or Terms will be substituted reflecting our intent as closely as possible. You may not assign any of your rights under these Terms, and any attempt to do so will be void. 180Credit may assign its rights to any of its affiliates or subsidiaries, or to any successor in interest of any business associated with the Services.
            <br><br><b>18. Questions and contact information</b><br>
            If you have any question regarding the use of the Site, please refer first to the FAQ. All other questions or comments about the Site or its contents should be directed to Customer Care or call us at (206) 734-4111.

        </p>
    </div>
</div>